from ai.generator import AIGenerator

from config.settings import (
    MAX_REFINEMENT_ITERATIONS,
)

from models.requests import StudyPackRequest

from utils.errors import WorkflowError

from workflow.assessment import (
    run_assessment_stage,
)

from workflow.content import (
    run_content_stage,
)

from workflow.planning import (
    run_planning_stage,
)

from workflow.refinement import (
    run_refinement_stage,
)

from workflow.review import (
    run_review_stage,
)

from workflow.state import WorkflowState


def run_workflow(
    api_key: str,
    request: StudyPackRequest,
    progress_callback=None,
) -> WorkflowState:
    """
    Run the complete AI study-pack workflow.

    Workflow:

        1. Planning
        2. Content Generation
        3. Assessment
        4. Review
        5. Refinement (if required)

    The stages pass their results forward so that every
    stage has access to the context generated by previous stages.
    """

    # ==========================================================
    # INITIALIZE WORKFLOW STATE
    # ==========================================================

    state = WorkflowState(
        user_request=request
    )

    # ==========================================================
    # INITIALIZE AI GENERATOR
    # ==========================================================

    try:
        generator = AIGenerator(
            api_key=api_key
        )

    except Exception as error:
        raise WorkflowError(
            "Failed to initialize the AI generator: "
            f"{type(error).__name__}: {error}"
        ) from error

    # ==========================================================
    # PROGRESS HELPER
    # ==========================================================

    def progress(
        stage: str,
        status: str,
        message: str = "",
    ) -> None:
        """
        Send workflow progress to the UI.

        The callback is optional so the workflow can also
        be used without Streamlit.
        """

        if progress_callback is not None:
            try:
                progress_callback(
                    stage,
                    status,
                    message,
                )
            except Exception:
                # Progress-display errors should never
                # break the actual AI workflow.
                pass

    # ==========================================================
    # STAGE 1 — PLANNING
    # ==========================================================

    try:
        progress(
            "Planning",
            "running",
            "Creating your personalized study plan...",
        )

        state.study_plan = run_planning_stage(
            generator,
            request,
        )

        state.mark_complete(
            "Planning"
        )

        progress(
            "Planning",
            "complete",
            "Study plan created.",
        )

    except Exception as error:
        state.add_error(
            "Planning",
            str(error),
        )

        progress(
            "Planning",
            "failed",
            str(error),
        )

        raise WorkflowError(
            "Planning stage failed: "
            f"{type(error).__name__}: {error}"
        ) from error

    # ==========================================================
    # STAGE 2 — CONTENT GENERATION
    # ==========================================================

    try:
        progress(
            "Content Generation",
            "running",
            "Generating study notes and learning material...",
        )

        state.study_content = run_content_stage(
            generator,
            request,
            state.study_plan,
        )

        state.mark_complete(
            "Content Generation"
        )

        progress(
            "Content Generation",
            "complete",
            "Study content generated.",
        )

    except Exception as error:
        state.add_error(
            "Content Generation",
            str(error),
        )

        progress(
            "Content Generation",
            "failed",
            str(error),
        )

        raise WorkflowError(
            "Content generation stage failed: "
            f"{type(error).__name__}: {error}"
        ) from error

    # ==========================================================
    # STAGE 3 — ASSESSMENT
    # ==========================================================

    try:
        progress(
            "Assessment",
            "running",
            "Creating questions and answer keys...",
        )

        state.assessment = run_assessment_stage(
            generator,
            request,
            state.study_plan,
            state.study_content,
        )

        state.mark_complete(
            "Assessment"
        )

        progress(
            "Assessment",
            "complete",
            "Assessment generated.",
        )

    except Exception as error:
        state.add_error(
            "Assessment",
            str(error),
        )

        progress(
            "Assessment",
            "failed",
            str(error),
        )

        raise WorkflowError(
            "Assessment stage failed: "
            f"{type(error).__name__}: {error}"
        ) from error

    # ==========================================================
    # STAGES 4 + 5
    #
    # REVIEW → REFINEMENT → REVIEW
    # ==========================================================

    for iteration in range(
        MAX_REFINEMENT_ITERATIONS + 1
    ):

        state.refinement_iteration = iteration

        # ======================================================
        # STAGE 4 — REVIEW
        # ======================================================

        try:
            progress(
                "Review",
                "running",
                (
                    "Checking study-pack quality "
                    f"(review attempt {iteration + 1})..."
                ),
            )

            state.review = run_review_stage(
                generator,
                request,
                state.study_plan,
                state.study_content,
                state.assessment,
            )

            state.mark_complete(
                "Review"
            )

            progress(
                "Review",
                "complete",
                "Study pack reviewed.",
            )

        except Exception as error:
            state.add_error(
                "Review",
                str(error),
            )

            progress(
                "Review",
                "failed",
                str(error),
            )

            raise WorkflowError(
                "Review stage failed: "
                f"{type(error).__name__}: {error}"
            ) from error

        # ======================================================
        # CHECK REVIEW RESULT
        # ======================================================

        approved = bool(
            state.review.get(
                "approved",
                False,
            )
        )

        # ======================================================
        # APPROVED → CREATE FINAL PACK
        # ======================================================

        if approved:

            state.final_pack = {
                # Full study plan
                "study_plan": state.study_plan,

                # Generated content
                "overview": state.study_content.get(
                    "overview",
                    "",
                ),

                "learning_objectives": state.study_content.get(
                    "learning_objectives",
                    [],
                ),

                "key_concepts": state.study_content.get(
                    "key_concepts",
                    [],
                ),

                "definitions": state.study_content.get(
                    "definitions",
                    [],
                ),

                "detailed_notes": state.study_content.get(
                    "detailed_notes",
                    [],
                ),

                "examples": state.study_content.get(
                    "examples",
                    [],
                ),

                "common_mistakes": state.study_content.get(
                    "common_mistakes",
                    [],
                ),

                "flashcards": state.study_content.get(
                    "flashcards",
                    [],
                ),

                "quick_revision": state.study_content.get(
                    "quick_revision",
                    [],
                ),

                # Assessment
                "mcqs": state.assessment.get(
                    "mcqs",
                    [],
                ),

                "short_answer_questions": state.assessment.get(
                    "short_answer_questions",
                    [],
                ),

                "long_answer_questions": state.assessment.get(
                    "long_answer_questions",
                    [],
                ),

                "answer_key": state.assessment.get(
                    "answer_key",
                    [],
                ),

                # Quality review
                "review": state.review,
            }

            progress(
                "Complete",
                "complete",
                "Your study pack is ready!",
            )

            return state

        # ======================================================
        # REFINEMENT LIMIT REACHED
        # ======================================================

        if (
            iteration
            >= MAX_REFINEMENT_ITERATIONS
        ):

            progress(
                "Refinement",
                "failed",
                (
                    "Maximum refinement attempts "
                    "reached."
                ),
            )

            raise WorkflowError(
                "The study pack did not pass quality "
                "review after "
                f"{MAX_REFINEMENT_ITERATIONS} "
                "refinement attempts."
            )

        # ======================================================
        # STAGE 5 — REFINEMENT
        # ======================================================

        try:
            progress(
                "Refinement",
                "running",
                (
                    "Improving the study pack based "
                    "on review feedback..."
                ),
            )

            refined = run_refinement_stage(
                generator,
                request,
                state.study_plan,
                state.study_content,
                state.assessment,
                state.review,
            )

            # ==================================================
            # EXTRACT REFINED CONTENT
            # ==================================================

            content_fields = [
                "overview",
                "learning_objectives",
                "key_concepts",
                "definitions",
                "detailed_notes",
                "examples",
                "common_mistakes",
                "flashcards",
                "quick_revision",
            ]

            missing_content = [
                field
                for field in content_fields
                if field not in refined
            ]

            if missing_content:
                raise WorkflowError(
                    "Refinement response is missing "
                    "content fields: "
                    + ", ".join(
                        missing_content
                    )
                )

            state.study_content = {
                field: refined[field]
                for field in content_fields
            }

            # ==================================================
            # EXTRACT REFINED ASSESSMENT
            # ==================================================

            assessment_fields = [
                "mcqs",
                "short_answer_questions",
                "long_answer_questions",
                "answer_key",
            ]

            missing_assessment = [
                field
                for field in assessment_fields
                if field not in refined
            ]

            if missing_assessment:
                raise WorkflowError(
                    "Refinement response is missing "
                    "assessment fields: "
                    + ", ".join(
                        missing_assessment
                    )
                )

            state.assessment = {
                field: refined[field]
                for field in assessment_fields
            }

            progress(
                "Refinement",
                "complete",
                (
                    "Study pack refined. "
                    "Running another quality review..."
                ),
            )

        except Exception as error:

            state.add_error(
                "Refinement",
                str(error),
            )

            progress(
                "Refinement",
                "failed",
                str(error),
            )

            raise WorkflowError(
                "Refinement stage failed: "
                f"{type(error).__name__}: {error}"
            ) from error

    # ==========================================================
    # SAFETY FALLBACK
    # ==========================================================

    raise WorkflowError(
        "Workflow ended without producing "
        "a final study pack."
    )